baseURL = "https://empireforhugotheme.site/"
languageCode = "en-us"
title = "Empire Podcast Network"
themesdir = "../.."
theme = "empire"

Paginate = 3

[params]
  # Specify light/dark colorscheme
  # Supported values:
  # "auto" (use preference set by browser)
  # "dark" (dark background, light foreground)
  # "light" (light background, dark foreground) (default)
  colorscheme = "auto"
  brandImage = "DeathStar.png"
  copyright_notice = "Copyright 2020 [Vic Hudson](https://vichudson1.com) & [Scott Willsey](https://scottwillsey.com)"

  description = "Serving all of The Empire's podcast listening needs."

  searchPageTitle = "Search The Empire"
  searchPlaceholderText = "Tear this ship apart and find me those plans"

[outputFormats]
  [outputFormats.jsonfeed]
    mediaType = "application/json"
    baseName = "feed"
    isPlainText = true
  [outputFormats.showslist]
    mediaType = "text/html"
    baseName = "index"
    isPlainText = false
    path = "shows"
  [outputFormats.search]
    mediaType = "text/html"
    baseName = "index"
    isPlainText = false
    path = "search"

[outputs]
  home = ["html", "rss", "showslist", "json", "search"]
  page = ["html"]
  section = ["html", "rss", "showslist"]

[menu]

[[menu.main]]
  name = "Home"
  weight = 1
  url = "/"
  
[[menu.main]]
  name = "Shows"
  weight = 2
  url = "shows/"

[[menu.main]]
  name = "Hosts"
  weight = 4
  url = "hosts/"
  
[[menu.main]]
  name = "Guests"
  weight = 5
  url = "guests/"

[[menu.main]]
  name = "About"
  weight = 6
  url = "about/"

[[menu.main]]
  pre = "<i class='fas fa-search'></i>"
  name = "Search"
  weight = 10
  url = "search/"