baseURL = "https://empireforhugothe.me"
languageCode = "en-us"
title = "Empire Podcast Network"
themesdir = "../.."
theme = "empire"

Paginate = 3

[outputFormats]
  [outputFormats.jsonfeed]
    mediaType = "application/json"
    baseName = "feed"
    isPlainText = true
  [outputFormats.showslist]
    mediaType = "text/html"
    baseName = "index"
    isPlainText = false
    path = "shows"

[outputs]
  home = ["html", "rss", "showslist"]
  page = ["html"]
  section = ["html", "rss", "showslist"]

[menu]

[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
  post = "navigation-link"

[[menu.main]]
  name = "Hosts"
  weight = 2
  url = "hosts/"
  post = "navigation-link"

[params]
copyright_notice = "Copyright 2020 [Vic Hudson](https://vichudson1.com) & [Scott Willsey](https://scottwillsey.com)"